# SPDX-FileCopyrightText: 2023 Vasco Dias <m+git@vascorsd.com>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"

services:
  gitea-server:
    image: gitea/gitea:latest-rootless
    restart: always
    volumes:
      - v-gitea:/data


volumes:
  v-gitea:
    driver: local
        
